### ISSUE TITLE
Diseñador de software: Definir lineamientos para el código  (estándares del equipo) -Integrar clases – Generar  migraciones.

### ISSUE THREAD

**Issue by Tigucaro** [Brilliant-Minds-Group/Mascota-Feliz#10]

**Comment by yaroa58** [comment]
lineamientos para el código:
==>**Herramientas:** 

- > VisualStudioCode: A través de éste editor de texto haremos los cambios correspondientes para iniciar con el proyecto, cada uno tendrá definido las clases correspondientes para poder iniciar con las modificaciones y luego para su posterior unión

> Se realizan las migraciones correspondientes a la base de datos Azure 


![Image](https://user-images.githubusercontent.com/107338903/187236494-ec46e717-e013-4712-95d2-f07d56c5416d.png)



- >Integración de clases: imagen adjuntada 

![Image](https://user-images.githubusercontent.com/107338903/187234234-f45ffd91-8878-48a9-b772-7d12a3e87d56.png)

Migraciones Generadas 


![Image](https://user-images.githubusercontent.com/107338903/187236739-a8dc6292-3e51-417e-9b86-69bee506087e.png)
