### ISSUE TITLE
El sistema debe permitir el registro de un nuevo propietario

### ISSUE THREAD

**Issue by Tigucaro** [Brilliant-Minds-Group/Mascota-Feliz#14]

**Comment by yaroa58** [comment]
Registro de usuario en proceso

![Image](https://user-images.githubusercontent.com/107338903/187275493-212fcc9f-a64e-46b2-999e-fc51cd6f1b01.png)

**Comment by yaroa58** [comment]
Terminación de ingreso de propietario

![Image](https://user-images.githubusercontent.com/107338903/187316425-36815ce3-e648-4425-a85e-68c6ce46aa7e.png)

**Comment by yaroa58** [comment]
`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="Estilos.css">

    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <title>Registro Propietario</title>
</head>

<body>
    <section class="registro">
        <div class="formulario">
            <h4>Formulario de Registro</h4>
            <input class="controls" type="text" name="datos" id="datos" placeholder="Ingrese su ID">
            <input class="controls" type="text" name="nombre" id="nombre" placeholder="Ingrese su Nombre">
            <input class="controls" type="text" name="apellidos" id="apellidos" placeholder="Ingrese su Apellido">
            <input class="controls" type="text" name="direccion" id="direccion" placeholder="Ingrese su Direccion">
            <input class="controls" type="text" name="telefono" id="telefono" placeholder="Ingrese su Teléfono">
            <input class="controls" type="email" name="correo" id="correo" placeholder="Ingrese su Correo">
            <p>Estoy deacuerdo con los terminos y condiciones</p>
            <input class="boton" type="submit" value="Registrarse">
            <p><a href="#">Ya tengo cuenta</a></p>
        </div>
    </section>

</body>

</html>`

CSS
`

*{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Open Sans', sans-serif;
    
}
body{
    background-image: url(fondo/fondo.jpg);
    background-repeat: no-repeat;
    background-size: cover;
}
.registro{
    width: 400px;
    background: #24303c;
    padding: 30px;
    margin: auto;
    margin-top: 100px;
    border-radius: 4px;
    font-family: 'Open Sans', sans-serif;
    color:aliceblue;
    box-shadow: 7px 13px 37px #000;
}

.registro h4{
    font-size: 24px;
    margin-bottom: 20px;
    
}

.controls{
    width: 100%;
    background: #24303c;
    padding: 10px;
    border-radius: 4px;
    margin-bottom: 10px;
    border: 1px solid #1f53c5;

    font-size: 15px;
    color: aliceblue;
}

.registro p{
    height: 40px;
    text-align: center;
    font-size: 14px;
    line-height: 40px;
}
.registro a{
    color: aliceblue;
    font-size: 14px;
    text-decoration: none;
   

}

.registro .boton{
    width: 100%;
    background: #1f53c5;
    border: none;
    padding: 12px;
    color: aliceblue;
    margin: 16px 0;
    font-size: 16px;
}`

**Comment by yaroa58** [comment]
`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="Estilos.css">

    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <title>Registro Propietario</title>
</head>

<body>
    <section class="registro">
        <div class="formulario">
            <h4>Formulario de Registro</h4>
            <input class="controls" type="text" name="datos" id="datos" placeholder="Ingrese su ID">
            <input class="controls" type="text" name="nombre" id="nombre" placeholder="Ingrese su Nombre">
            <input class="controls" type="text" name="apellidos" id="apellidos" placeholder="Ingrese su Apellido">
            <input class="controls" type="text" name="direccion" id="direccion" placeholder="Ingrese su Direccion">
            <input class="controls" type="text" name="telefono" id="telefono" placeholder="Ingrese su Teléfono">
            <input class="controls" type="email" name="correo" id="correo" placeholder="Ingrese su Correo">
            <p>Estoy deacuerdo con los terminos y condiciones</p>
            <input class="boton" type="submit" value="Registrarse">
            <p><a href="#">Ya tengo cuenta</a></p>
        </div>
    </section>

</body>

</html>`
