### ISSUE TITLE
El sistema debe permitir el registro de un nuevo veterinario

### ISSUE THREAD

**Issue by Tigucaro** [Brilliant-Minds-Group/Mascota-Feliz#15]

**Comment by LeanCano** [comment]
![Image](https://user-images.githubusercontent.com/111925428/187947754-52e92a44-2559-4f13-9373-d022c42043a9.jpg)

**Comment by LeanCano** [comment]
`<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="refresh" content="30">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Registro veterinario</title>
    <link rel="stylesheet" href="style.css">
    <style> </style> 
</head>

<body>
<div class="container">
    <H2>REGISTRATE</H2>
    <input class="controls" type="text" name="nombres" id="nombres" placeholder="Nombre completo"><br>
    <input class="controls" type="text" name="apellidos" id="apellidos" placeholder="Apellidos"><br>
    <input class="controls" type="text" name="nombres" id="nombres" placeholder="Dirección de vivienda"><br>
    <input class="controls" type="text" name="nombres" id="nombres" placeholder="Número de teléfono"><br>
    <input class="controls" type="text" name="nombres" id="nombres" placeholder="Tarjeta profesional"><br>
    <input class="button" type="submit" value="Registrar"><br>
    <p>Al registrarte, aceptas nuestras <a href="#">condiciones de uso y política de privacidad</a></p>
    
</div>

</body>

</html>`

**Comment by LeanCano** [comment]
style.css

`*{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}
body{
    width: 100%;
    min-height: 100vh;
    display: flex;
    justify-content:center ;
    align-items: center;
    background: linear-gradient(to top right, rgb(138, 140, 231) 5%, rgb(92, 150, 236) 100% );

}
.container{
    margin: auto;
    width: 400px;
    padding: 30px ;
    background: rgb(133, 243, 142);
    border-radius: 8px;
}
.controls{
    width: 100%;
    padding: 12px;
    margin-bottom: 15px;
    border-radius: 4px;
    border: 1px solid rgb(2, 245, 15);

}
.button{
    width: 100%;
    padding: 12px;
    margin-bottom: 15px;
    border: none;
    background: goldenrod;
    font-size: 16 px;


}
.container h2{
    padding: 18px;
    align-self: center;
    text-align: center;

}
.container p{
    text-align: center;
    height: 40px;
}`
