### ISSUE TITLE
El sistema debe permitir consultar el listado de todas las mascotas

### ISSUE THREAD

**Issue by Tigucaro** [Brilliant-Minds-Group/Mascota-Feliz#17]

**Comment by CarlosECorreaH** [comment]
![Image](https://user-images.githubusercontent.com/112055577/188260586-1597fa63-2405-40de-84fc-6557ebfbfec9.png)

**Comment by CarlosECorreaH** [comment]
Codigo de estilos

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    background: #FDC830;
    background: -webkit-linear-gradient(to right, #F37335, #FDC830);
    background: linear-gradient(to right, #F37335, #FDC830);
}

.consulta {
    width: 400px;
    background: #24303c;
    padding: 30px;
    margin: auto;
    margin-top: 100px;
    border-radius: 4px;
    font-family: 'Open Sans', sans-serif;
    color: white;
    box-shadow: 7px 13px 37px #000;
}

.consulta h2 {
    font-size: 24px;
    margin-bottom: 20px;
}

.consulta .boton {
    width: 100%;
    background: #FDC830;
    background: -webkit-linear-gradient(to right, #F37335, #FDC830);
    background: linear-gradient(to right, #F37335, #FDC830);
    border: none;
    padding: 12px;
    color: white;
    font-size: 18px;
}

**Comment by CarlosECorreaH** [comment]
### Codigo formulario

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="Estilos.css">
    <title>Consultas</title>
</head>

<body>
    <section class="consulta">
        <h2>Listas de registros</h2>

        <form action="/action_page.php">

            <input class="boton" type="submit" value="Listado Mascotas">
        </form>
    </section>
</body>


</html>
