### ISSUE TITLE
Líder: Implementar clases asignadas – Elaborar informe de  seguimiento – Explorar herramienta para prototipos de UI.

### ISSUE THREAD

**Issue by OscarMLopezI** [Brilliant-Minds-Group/Mascota-Feliz#7]

**Comment by Tigucaro** [comment]
EVIDENCIAS DE LA IMPLEMENTACIÓN DE LAS CLASES-CAPA DOMINIO.
•	CLASE DUEÑO 



![Image](https://user-images.githubusercontent.com/111239053/187232506-92bef360-9a74-4cc6-94ca-191bee15330b.png)


•	CLASE HISTORIA 


![Image](https://user-images.githubusercontent.com/111239053/187232553-94f91351-a96f-4ca3-8d90-8621893b79d1.png)



•	CLASE MASCOTA
 


![Image](https://user-images.githubusercontent.com/111239053/187232895-7c22cae8-5cf3-4035-bc46-84d4cb2018d3.png)




•	CLASE PERSONA


![Image](https://user-images.githubusercontent.com/111239053/187232952-520e787e-9605-40cf-be72-97ea552a4005.png)


 

•	CLASE VETERINARIO
 

![Image](https://user-images.githubusercontent.com/111239053/187232988-b2ce9b91-b878-4a08-a25b-2c80fc49a25e.png)





•	CLASE VISITAPYP
 


![Image](https://user-images.githubusercontent.com/111239053/187233049-334c3da5-7d4b-4482-a88d-ed3c6912032e.png)

**Comment by Tigucaro** [comment]
HERRAMIENTAS PARA MANEJAR PROTOTIPOS UI

[Herramientas para crear prototipos de UI.docx](https://github.com/Brilliant-Minds-Group/Mascota-Feliz/files/9445695/Herramientas.para.crear.prototipos.de.UI.docx)

**Comment by Tigucaro** [comment]
[Informe de Seguimiento 1.docx](https://github.com/Brilliant-Minds-Group/Mascota-Feliz/files/9462528/Informe.de.Seguimiento.1.docx)
