### ISSUE TITLE
Diseñador de UI: Definir lineamientos para el diseño de la UI  (estilo) – Implementar clases asignadas – Explorar  herramientas para prototipos de UI.

### ISSUE THREAD

**Issue by Tigucaro** [Brilliant-Minds-Group/Mascota-Feliz#9]

**Comment by CarlosECorreaH** [comment]
Implementación de las clases en la 

 Dueño.

![Image](https://user-images.githubusercontent.com/112055577/187839588-386488c1-b7ec-4002-9eb7-00e4622bc535.PNG)

Historia

![Image](https://user-images.githubusercontent.com/112055577/187839830-19e43d2c-84c9-4211-8682-ff7ee3b4a593.PNG)

Mascota.

![Image](https://user-images.githubusercontent.com/112055577/187839899-ccd054ef-bb3a-4a9d-a6ea-4c393b7c4b22.PNG)


Persona.

![Image](https://user-images.githubusercontent.com/112055577/187839935-b5b4ee65-250b-4b3f-86c9-73277c5cf600.PNG)

Veterinario.


![Image](https://user-images.githubusercontent.com/112055577/187840030-493152d1-fa57-45cc-b95b-cc07abcddd40.PNG)


VisitaPyP

![Image](https://user-images.githubusercontent.com/112055577/187840070-f18a6246-d4e5-41c3-9f17-6d7b75ec7e46.PNG)

**Comment by CarlosECorreaH** [comment]
Investigación de herramientas de UI enfocado en en ventajas o características principales.


[Herramientas para la creación de prototipos UI.docx](https://github.com/Brilliant-Minds-Group/Mascota-Feliz/files/9467542/Herramientas.para.la.creacion.de.prototipos.UI.docx)

**Comment by CarlosECorreaH** [comment]
### **Lineamientos estándar de diseño**

- Se propinen fondos claros y coloridos.
- Con cuerpos de texto claros (Blanco) de fondo oscuro (Negro).
- tipo de letra TIMES NEW ROMAN
- Tamaño 12
- Mas grande el tamaño para los títulos.
- Botones coloridos 

nota:  Se habla en las reuniones con el equipo para definir como equipo el uso o el cambio de estos lineamientos.
